apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
    # - name: websecure
    #   port: 443
    #   protocol: TCP
    #   targetPort: websecure
  selector:
    app.kubernetes.io/instance: phpmyadmin
    app.kubernetes.io/name: phpmyadmin