cluster:
  mode: standalone
  cluster:
    instances: 1
    primaryUpdateStrategy: unsupervised
    roles:
      - name: dante
        ensure: present
        comment: testdb
        login: true
        superuser: false
        passwordSecret:
          name: cluster-additional-db
    initdb:
      database: semaphore
      owner: semaphore
      secret: 
        name: postgres-user
    storage:
      size: 5Gi
      storageClass: standard
    resources:
      requests: 
        cpu: 50m
        memory: 500Mi
      limits:
        cpu: 50m
        memory: 1Gi
    priorityClassName: ""
