cluster:
  mode: standalone
  cluster:
    instances: 1
    primaryUpdateStrategy: unsupervised
    priorityClassName: ""
    managed: ""
    initdb:
      database: semaphore
      owner: semaphore
      secret: postgres-user
    storage:
      size: 5Gi
      storageClass: standard
    resources:
      requests: 
        cpu: 15m
        memory: 250M
      limits:
        cpu: 15m
        memory: 300M
  backups:
    enabled: false
