apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.21.2
    releaseName: cnpg-operator
    namespace: cnpg-system
    valuesFile: values.yaml
