---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../argocd-manifest

patchesStrategicMerge:
  - overlays/argocd-cmd-params-cm.yaml
  - overlays/argocd-rbac-cm.yaml
  - overlays/argo-cd-cm.yaml

#images:
  #- name: quay.io/argoproj/argocd
    #newTag: v2.12.3
