argo-cd:
  configs:
    cm:
      create: true
      admin.enabled: "true"
      kustomize.buildOptions: --enable-helm
    #cmp:
    # create: true
    # plugins:
    #   kustomize-build-with-helm:
    #     generate:
    #       command: [ "sh", "-c" ]
    #       args: [ "kustomize build --enable-helm" ]
    params:
      server.insecure: true
    rbac:
      create: true
      scopes: '[groups]'
      policy.csv: |
        g, argocd_administrators, role:admin
        g, argocd_users, role:readonly
      policy.default: ''

  crds:
    install: true
    # -- Keep CRDs on chart uninstall
    keep: false

  #repoServer:
  #  extraContainers:
  #    - name: kustomize-build-with-helm
  #      command:
  #        - argocd-cmp-server
  #      image: '{{ default .Values.global.image.repository .Values.repoServer.image.repository }}:{{ default (include "argo-cd.defaultTag" .) .Values.repoServer.image.tag }}'
  #      securityContext:
  #        runAsNonRoot: true
  #        runAsUser: 999
  #      volumeMounts:
  #        - name: plugins
  #          mountPath: /home/argocd/cmp-server/plugins
  #        - name: cmp-kustomize-build-with-helm
  #          mountPath: /home/argocd/cmp-server/config/plugin.yaml
  #          subPath: kustomize-build-with-helm.yaml
  #        - mountPath: /tmp
  #          name: cmp-tmp
  #  volumes:
  #    - name: cmp-kustomize-build-with-helm
  #      configMap:
  #        name: argocd-cmp-cm
  #    - name: cmp-tmp
  #      emptyDir: { }
