apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ilbarone87/testing
        revision: HEAD
        directories:
          - path: secrets/*
  template:
    metadata:
      name: '{{ path.basename }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/ilbarone87/testing
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
